from flask import Flask, render_template
from scrapers.ncaa_hockey_scraper import run_scraper
from elo.elo_builder import build_elo_table, get_rankings
from elo.schedule_utils import get_team_schedule
import os

# Only import and refresh locally, not on Render
if os.environ.get("RENDER") is None:
    import refresh_elo
    refresh_elo.daily_refresh()


app = Flask(__name__)

# Initialize
last_updated = "Unknown"

# Load data generated by refresh_elo.py
all_games, regular_season, games_df = run_scraper()

timestamp_path = os.path.join("data", "last_updated.txt")
if os.path.exists(timestamp_path):
    with open(timestamp_path, "r") as f:
        last_updated = f.read().strip()

# Build Elo table for display
elo_table = build_elo_table(regular_season)
team_slug_map = {row['team_slug']: row['team'] for row in elo_table}
display_name_map = {row['team_slug']: row['display_name'] for row in elo_table}

@app.route('/')
def show_rankings():
    return render_template('elo_rankings.html', elo_table=elo_table, last_updated=last_updated)

@app.route('/schedule/<path:team_name>')
def show_team_schedule(team_name):
    schedule = get_team_schedule(team_name, all_games.to_dict(orient='records'))
    return render_template('schedule.html', team_name=team_name, schedule=schedule)

if __name__ == '__main__':
    app.run(debug=True)